version: "3"
services:
  nginx:
    container_name: lmay-nginx
    image: nginx:1.16
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx

  mysql:
    container_name: lmay-mysql
    image: mysql:8.0.16
    environment:
      MYSQL_DATABASE: spring-boot-docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      # 初始化数据脚本
      - ./mysql/init:/docker-entrypoint-initdb.d/

  spring-boot-docker-compose:
    container_name: spring-boot-docker-compose
    image: lmay/spring-boot-docker-compose:1.0
    restart: always
    working_dir: /spring-boot-docker-compose
    volumes:
      - ./logs:/usr/local/logs
    ports:
      - 83:83
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
