# 服务端口
server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    name: SqlToy
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER:lms-mysql:3306}/sql_toy?allowMultiQueries=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 2
      connection-timeout: 30000
      idle-timeout: 30000
      connection-test-query: select 1
  sqltoy:
    # 多个路径用逗号分隔(这里要注意是路径,sqltoy会自动向下寻找以sql.xml结尾的文件,不要写成classpath:com/**/*.sql.xml)
    sqlResourcesDir: classpath:/mapper
    # 默认值为classpath:sqltoy-translate.xml，一致则可以不用设置
    translateConfig: classpath:sqltoy-translate.xml
    # 针对json等特殊类型做处理(可选配置)
#    typeHandler: com.sqltoy.plugins.JsonTypeHandler
    # 默认开启跨数据库函数自动适配(如oracle的nvl,当数据库切到mysql时会自动替换成ifnull)
#    functionConverts: default
    # 默认为false，debug模式将打印执行sql,并自动检测sql文件更新并重新加载
    debug: true
    # 提供统一字段:createBy createTime updateBy updateTime 等字段补漏性(为空时)赋值(可选配置)
#    unifyFieldsHandler: com.sqltoy.plugins.SqlToyUnifyFieldsHandler
    # sql执行超过多长时间则进行日志输出,用于监控哪些慢sql(可选配置:默认30秒)
    printSqlTimeoutMillis: 300000
    # 分页最大提取数据限制，默认10万
#    pageFetchSizeLimit: 500000
    # 数据库保留字兼容处理(原则上不要使用数据库保留字,多个用逗号分隔)
#    reservedWords: maxvalue,minvalue
    # 切换缓存类型，默认为ehcache(在sqltoy中缓存存放cache[cacheName,HashMap<key,Object[]]结构,所以缓存框架并不影响性能)
#    cacheType: caffeine
    # 自定义缓存框架设定
#    translateCacheManager: com.xxxx.xxxCacheImpl
    # 使用sqltoy自带的RSA加解密
#    securePrivateKey: classpath:mock/rsa_private.key
#    securePublicKey: classpath:mock/rsa_public.key
    # 自定义加解密实现
#    fieldsSecureProvider: 可自行实现org.sagacity.sqltoy.plugins.secure.FieldsSecureProvider

# Swagger 配置
springfox:
  documentation:
    enabled: true
swagger:
  title: Microservice API-在线接口文档
  description: LmayE Software, Inc.
  version: 1.0.1
  termsOfServiceUrl: https://www.lmaye.com
  basePackage: com.lmaye.sqltoy.controller
  basePath: /**
  excludePath: /error
  contact:
    email: lmay@lmaye.com
    name: lmay Zhou
    url: https://www.lmaye.com
  global-operation-parameters:
    - description: 凭证
      modelRef: string
      name: Authorization
      parameterType: header
      required: true