package rules;
dialect  "mvel"
import com.lmaye.cloud.example.drools.entity.Person

rule "personRule1"
    when $person:Person(age <= 6)
    then
        $person.setDesc($person.getName() + " is Infant!");
        System.out.println($person.getDesc());
end

rule "personRule2"
    when $person:Person(age >= 7 && age <= 12)
    then
        $person.setDesc($person.getName() + " is Children!");
        System.out.println($person.getDesc());
end

rule "personRule3"
    when $person:Person(age >= 13 && age <= 17)
    then
        $person.setDesc($person.getName() + " is Teenager!");
        System.out.println($person.getDesc());
end

rule "personRule4"
    when $person:Person(age >= 18 && age <= 45)
    then
        $person.setDesc($person.getName() + " is Young!");
        System.out.println($person.getDesc());
end