# 服务配置
server:
  port: 70

# spring 配置
spring:
  application:
    name: websocket
  freemarker:
    suffix: .ftl
    content-type: text/html
    # 缓存配置
    cache: false
    template-loader-path: classpath:/templates
    # 编码格式
    charset: UTF-8
    settings:
      # 数字格式化，无小数点
      number_format: '0.##'
