# 服务端口
server:
  port: 8080

# Spring 配置
spring:
  application:
    # 应用名称
    name: spring-boot-amqp
  # MQ
  rabbitmq:
    host: amqp-cn-xxx.mq-amqp.cn-hangzhou-249959-a.aliyuncs.com
    virtual-host: xxx
    username: xxx
    password: xxx
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true