# Spring 配置
spring:
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    process-definition-location-prefix: classpath:**/processes
    # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exp_activiti?allowMultiQueries=true&useSSL=false&characterEncoding=utf8&nullCatalogMeansCurrent=true
    username: root
    password: root
    hikari:
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 2
      connection-timeout: 30000
      idle-timeout: 30000
      connection-test-query: select 1
  security:
    user:
      name: admin
      password: admin

# version初始化异常处理
project:
  manifest:
    file:
      path: classpath:/default-project.json

#logging:
#  level:
#    com.len.mapper: DEBUG
#    org.activiti.engine.impl.persistence.entity: debug

# Swagger 配置
swagger:
  enabled: true
  title: Activiti工作流 API-在线接口文档
  description: Activiti工作流 API-在线接口文档
  version: 1.0.1
  termsOfServiceUrl: https://www.lmaye.com
  basePackage: com.lmaye.activiti.controller
  basePath: /**
  excludePath: /error
  contact:
    email: lmay@lmaye.com
    name: lmay Zhou
    url: https://www.lmaye.com
  globalOperationParameters:
    - description: 凭证
      modelRef: string
      name: Authorization
      parameterType: header
      required: false
    - description: 国际化
      modelRef: string
      name: Accept-Language
      parameterType: header
      required: false

web:
  # I18n 国际化
  i18n:
    # 是否启用
    enabled: true
    # 自定义请求路径参数( ?locale=en-US ), 默认使用请求头参数( Accept-Language )
    localeName: locale
    # local分隔符, 与 localeName 组合使用
    localeDelimiter: "-"
