# Server properties
server:
  port: 66

# Spring properties
spring:
  application:
    name: webrtc
  # Templating properties
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/

# Log properties
logging:
  config: classpath:logback-spring.xml