# 服务配置
server:
  port: 60

# spring 配置
spring:
  application:
    name: elasticsearch
  output:
    ansi:
      enabled: always
  # ES
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300

# 日志配置
logging:
  config: classpath:log4j2.xml
