# 服务配置
server:
  port: 60

# spring 配置
spring:
  application:
    name: elasticsearch
  output:
    ansi:
      enabled: always
  # ES
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: es-cluster
      # stand alone nodes
#      cluster-nodes: "192.168.0.10:9300, 192.168.0.10:9301, 192.168.0.10:9302"
      # cluster nodes
      cluster-nodes: "192.168.0.110:9300, 192.168.0.111:9300, 192.168.0.112:9300"

# 日志配置
logging:
  config: classpath:log4j2.xml
