version: "3"
services:
  es-master:
    container_name: es-master
    hostname: es-master
    image: elasticsearch:7.9.3
    restart: "no"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./conf/es-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  es-head:
    container_name: es-head
    image: mobz/elasticsearch-head:5
    restart: "no"
    ports:
      - 9100:9100
    depends_on:
      - es-master

  # 安装jdbc: bin/logstash-plugin install logstash-input-jdbc
  logstash:
    container_name: logstash
    hostname: logstash
    image: logstash:7.9.3
    restart: "no"
    volumes:
      - ./conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./conf/logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./sync-mysql-logs.conf:/usr/share/logstash/pipeline/sync-mysql-logs.conf
#      - ./mysql-connector-java-8.0.20.jar:/usr/share/logstash/mysql-connector-java-8.0.20.jar
    environment:
      - elasticsearch.hosts=http://es-master:9200
    ports:
      - 5044:5044
    depends_on:
      - es-master

  kibana:
    container_name: kibana
    hostname: kibana
    image: kibana:7.9.3
    restart: always
    ports:
      - 5601:5601
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - elasticsearch.hosts=http://es-master:9200
    depends_on:
      - es-master

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.5.5
    restart: "no"
    volumes:
      - ./data/zookeeper:/data
      - ./conf/zoo.cfg:/conf/zoo.cfg
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: "no"
    environment:
      - KAFKA_BROKER_ID=1
      # 主机IP
      - KAFKA_ADVERTISED_HOST_NAME=192.168.0.10
      - KAFKA_ADVERTISED_PORT=9092
#      - KAFKA_LISTENERS=PLAINTEXT://192.168.0.10:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_MESSAGE_MAX_BYTES=2000000
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafka-manager:
    container_name: kafka-manager
    image: sheepkiller/kafka-manager
    restart: "no"
    # 宿主机IP
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - 9000:9000

# 配置和其他容器互通的网络
networks:
  default:
    external:
      name: net-lmay